[package]
name = "common"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }
rust-version = { workspace = true }


[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }